services:
  init:
    image: bash:5
    command: /data/init/./init.sh
    volumes:
      - ./:/data
      - ganache:/ganache-data
      - aggregator:/aggregator-data
      - publisher-1:/publisher-1-data
      - publisher-2:/publisher-2-data
    network_mode: "host"
  ganache:
    build:
      context: ganache
      dockerfile: Dockerfile
    volumes:
      - ganache:/ganache-data
    network_mode: "host"
    depends_on:
      init:
        condition: service_completed_successfully
  aggregator:
    build:
      context: ../apps
      dockerfile: feed-aggregator.Dockerfile
    env_file: aggregator/.env
    volumes:
      - aggregator:/app-data
    network_mode: "host"
    depends_on:
      init:
        condition: service_completed_successfully
  publisher-1:
    build:
      context: ../apps
      dockerfile: feed-publisher.Dockerfile
    env_file: publisher-1/.env
    volumes:
      - publisher-1:/app-data
    network_mode: "host"
    depends_on:
      init:
        condition: service_completed_successfully
  publisher-2:
    build:
      context: ../apps
      dockerfile: feed-publisher.Dockerfile
    env_file: publisher-2/.env
    volumes:
      - publisher-2:/app-data
    network_mode: "host"
    depends_on:
      init:
        condition: service_completed_successfully

volumes:
  ganache:
  aggregator:
  publisher-1:
  publisher-2: